eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8801/eureka/
server:
  port: 8804
  servlet:
    context-path: /feign-consumer
spring:
  application:
    name: feign-consumer
feign:
  hystrix:
    enabled: true
